// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_Wym8jtW9d2q0WYeN8kcf6L18vejqzeA',
    appId: '1:890695973745:web:a1f6a7f6a711966c6f94d0',
    messagingSenderId: '890695973745',
    projectId: 'metrotrotter-589e1',
    authDomain: 'metrotrotter-589e1.firebaseapp.com',
    storageBucket: 'metrotrotter-589e1.appspot.com',
    measurementId: 'G-J59NCLLNFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUKo1-kTNssFd2SJUclCK_Er9YlN7nigY',
    appId: '1:890695973745:android:8292012179d5a6ea6f94d0',
    messagingSenderId: '890695973745',
    projectId: 'metrotrotter-589e1',
    storageBucket: 'metrotrotter-589e1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcSZiUpnPmIb1ikBWDTZmhK_KCtWg_LO8',
    appId: '1:890695973745:ios:5ce2fe0c44008a066f94d0',
    messagingSenderId: '890695973745',
    projectId: 'metrotrotter-589e1',
    storageBucket: 'metrotrotter-589e1.appspot.com',
    iosClientId: '890695973745-f6un8uj4jjnu14qp3aomv2sh1sqpgsql.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
